services:
  streamlit-pipeline-vbd-test:
    image: streamlit-pipeline-vbd-test:latest
    container_name: streamlit-pipeline-vbd-test
    ports:
      - "8501:8501"
    restart: always
    environment:
      - STORAGE_URL=${STORAGE_URL}
      - API_KEY=${API_KEY}
      - API_KEY_NAME=${API_KEY_NAME}
      - API_BASE_URL=${API_BASE_URL}
      - API_BASE_NAME=${API_BASE_NAME}
      - API_BASE_KEY=${API_BASE_KEY}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - OPENAI_API_KEY_ONCO=${OPENAI_API_KEY_ONCO}
      - OPENAI_API_KEY_CARDIO=${OPENAI_API_KEY_CARDIO}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_CONTAINER_NAME=${MONGO_CONTAINER_NAME}
      - WEAVIATE_CONTAINER_NAME=${WEAVIATE_CONTAINER_NAME}
      - WEAVIATE_API_KEY=${WEAVIATE_API_KEY}
      - LLAMA_CLOUD_API_KEY=${LLAMA_CLOUD_API_KEY}
    command: ["streamlit", "run", "main.py", "--server.port=8501"]
    networks:
      - pipline_vbd_network
  weaviate:
    image: semitechnologies/weaviate:1.30.14
    container_name: weaviate
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "false"
      AUTHENTICATION_APIKEY_ENABLED: "true"
      AUTHENTICATION_APIKEY_ALLOWED_KEYS: ${WEAVIATE_API_KEY}
      AUTHENTICATION_APIKEY_USERS: "admin"
      QUERY_DEFAULTS_LIMIT: 25
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      ENABLE_MODULES: "text2vec-openai"
      DEFAULT_VECTORIZER_MODULE: "text2vec-openai"
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: unless-stopped
    networks:
      - pipline_vbd_network

networks:
  pipline_vbd_network:
    external: true

volumes:
  weaviate_data: